# Generated by Django 2.0 on 2019-12-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_feadback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feadback',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
