# Generated by Django 2.0 on 2019-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191214_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(default='static/defaultuser.png', upload_to='images'),
        ),
    ]
