# Generated by Django 2.0 on 2019-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191220_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to='images'),
        ),
    ]
