# Generated by Django 2.0 on 2019-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191214_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feadback',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
