# Generated by Django 2.0 on 2019-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191220_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to='user/images'),
        ),
        migrations.AlterField(
            model_name='account',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
